### ISSUE TITLE
Scapi repository missing. 

### ISSUE THREAD

**Issue by abhishektyag1** [venkatarun95/SecureMultipartyComputation#1]
Hi, I am going to add functionality to the existing code. Could you please provide the old repository to the Scapi or suggest alternatives. 

Thanks.

**Comment by venkatarun95** [comment]
They have discontinued support for the Java  Scapi library. There is a version here: [https://github.com/ddunwoody/scapi](https://github.com/ddunwoody/scapi) Though it does not have the specific commit referenced in the repo, I expect it should work

However, I have put all the compiled jars in the `assets` folder, including `Scapi-2.4.jar`. Running the scripts as described in the readme works for me. If you are looking for a quick way to experiment with your protocols, you should be fine even without having to compile scapi from scratch. Let me know if you face any issues

**Comment by abhishektyag1** [comment]
Could you please recommend to me the IDE that you used to develop the code?

**Comment by venkatarun95** [comment]
I just used a text editor and the terminal. Just run the scripts in the README to get started, e.g. `src/compile` and `src/run`
